name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy docker-compose.yml to Hetzner Server and Rebuild
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          echo "$PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa

          # Send updated docker-compose.yml to server
          scp -o StrictHostKeyChecking=no -i id_rsa docker-compose.yml $USER@$HOST:/root/

          # SSH in, pull latest project code and rebuild
          ssh -o StrictHostKeyChecking=no -i id_rsa $USER@$HOST << 'EOF'
            cd /root/your-project-folder

            git pull origin main  # Pull latest code from GitHub
            cp /root/docker-compose.yml .  # Replace compose file if needed

            docker-compose build --no-cache
            docker-compose up -d --force-recreate
          EOF

          rm -f id_rsa
