name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Change branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .
          docker save my-app:latest > my-app.tar

      - name: Deploy to Hetzner Server
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Save the private key
          echo "$PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa

          # Transfer Docker image and compose file to the server
          ssh -o StrictHostKeyChecking=no -i id_rsa my-app.tar docker-compose.yml $USER@$HOST:/root/

          # SSH into the server and deploy
          ssh -o StrictHostKeyChecking=no -i id_rsa $USER@$HOST << 'EOF'
            docker load < /root/my-app.tar
            docker-compose -f /root/docker-compose.yml up -d --force-recreate
            rm -f /root/my-app.tar
          EOF

          # Cleanup the key
          rm -f id_rsa
